<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Catalyst" Version="26.3.60" />
    <PackageReference Include="Catalyst.Models.English" Version="1.0.30952" />
    <PackageReference Include="Catalyst.Models.Ukrainian" Version="1.0.30952" />
    <PackageReference Include="dotnet-stop-words" Version="1.1.0" />
    <PackageReference Include="NEST" Version="7.17.5" />
    <PackageReference Include="WeCantSpell.Hunspell" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="en_US.aff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="en_US.dic">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
